version: "3"
services:
  redis:
    image: redis
    restart: always
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: password # obviously not production friendly
  sidekiq:
    build: .
    command: bundle exec sidekiq
    environment:
      JOB: sidekiq
      RAILS_ENV: production
      NODE_ENV: production
    volumes:
      - ./app:/myapp/app
      - ./db:/myapp/db
      - ./config:/myapp/config
      - ./public:/myapp/public
      - ./config.ru:/myapp/config.ru
      - ./babel.config.js:/myapp/babel.config.js
      - ./.ruby-version:/myapp/.ruby-version
      - ./fake_users_create.rb:/myapp/fake_users_create.rb
      - ./postcss.config.js:/myapp/postcss.config.js
      - ./Rakefile:/myapp/Rakefile
      - ./.browserslistrc:/myapp/.browserslistrc
      - ./.env:/myapp/.env
    restart: always
    depends_on:
      - api
  api:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    environment:
      RAILS_ENV: production
      NODE_ENV: production
      WEBPACKER_DEV_SERVER_HOST: "0.0.0.0"
    volumes:
      - ./app:/myapp/app
      - ./db:/myapp/db
      - ./config:/myapp/config
      - ./public:/myapp/public
      - ./config.ru:/myapp/config.ru
      - ./babel.config.js:/myapp/babel.config.js
      - ./.ruby-version:/myapp/.ruby-version
      - ./fake_users_create.rb:/myapp/fake_users_create.rb
      - ./postcss.config.js:/myapp/postcss.config.js
      - ./Rakefile:/myapp/Rakefile
      - ./.browserslistrc:/myapp/.browserslistrc
      - ./.env:/myapp/.env
    restart: always
    ports:
      - "3000:3000"
      - "3035:3035" # webpack dev server (autoreload)
    depends_on:
      - db
      - redis
