development:
  adapter: redis
  url: <%= "redis://redis/" %>
  channel_prefix: myapp_development

test:
  adapter: async

production:
  adapter: redis
  url: <%= "redis://redis/" %>
  channel_prefix: myapp_production
